package criptare;
//package criptare;

import criptare.TransformareBS;
import static criptare.TransformareBS.Citire;
import criptare.Vernam;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Corina
 */
public class MeniuCriptare extends javax.swing.JFrame {

    /**
     * Creates new form MeniuCriptare
     */
    public MeniuCriptare() {
        
        initComponents();
        setTitle("File Encryption");
    }

         public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myOptionGroup = new javax.swing.ButtonGroup();
        PanelTextCript1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextCript1 = new javax.swing.JTextArea();
        PanelKey = new javax.swing.JPanel();
        OptList = new javax.swing.JComboBox<>();
        OpenButton = new javax.swing.JButton();
        PanelTextInit = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextInit = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        PanelTextCript = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextCript = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        BrowseField = new javax.swing.JTextField();
        Browse = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        PanelTextCript1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Encrypted text", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        TextCript1.setColumns(20);
        TextCript1.setLineWrap(true);
        TextCript1.setRows(5);
        TextCript1.setWrapStyleWord(true);
        TextCript1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane4.setViewportView(TextCript1);

        javax.swing.GroupLayout PanelTextCript1Layout = new javax.swing.GroupLayout(PanelTextCript1);
        PanelTextCript1.setLayout(PanelTextCript1Layout);
        PanelTextCript1Layout.setHorizontalGroup(
            PanelTextCript1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTextCript1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        PanelTextCript1Layout.setVerticalGroup(
            PanelTextCript1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTextCript1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(501, 501, 501))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Encryption Menu");
        setBackground(new java.awt.Color(153, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setLocation(new java.awt.Point(550, 200));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(900, 700));
        setSize(new java.awt.Dimension(900, 300));
        getContentPane().setLayout(null);

        PanelKey.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Key Generator", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial Narrow", 1, 16))); // NOI18N
        PanelKey.setNextFocusableComponent(OpenButton);

        OptList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SR", "bbs", "WichmannHill" }));
        OptList.setSelectedItem(OptList.getSelectedItem());
        OptList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        OptList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptListActionPerformed(evt);
            }
        });

        OpenButton.setText("Open ");
        OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKeyLayout = new javax.swing.GroupLayout(PanelKey);
        PanelKey.setLayout(PanelKeyLayout);
        PanelKeyLayout.setHorizontalGroup(
            PanelKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKeyLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(PanelKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKeyLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(OpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(OptList, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        PanelKeyLayout.setVerticalGroup(
            PanelKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKeyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OptList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OpenButton))
        );

        getContentPane().add(PanelKey);
        PanelKey.setBounds(290, 90, 328, 105);

        PanelTextInit.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input plain text", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14)), "Input plain text", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial Narrow", 1, 18))); // NOI18N
        PanelTextInit.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N

        TextInit.setColumns(20);
        TextInit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextInit.setLineWrap(true);
        TextInit.setRows(5);
        TextInit.setToolTipText("");
        TextInit.setWrapStyleWord(true);
        TextInit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextInit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextInit.setDragEnabled(true);
        TextInit.setEnabled(false);
        jScrollPane3.setViewportView(TextInit);

        javax.swing.GroupLayout PanelTextInitLayout = new javax.swing.GroupLayout(PanelTextInit);
        PanelTextInit.setLayout(PanelTextInitLayout);
        PanelTextInitLayout.setHorizontalGroup(
            PanelTextInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTextInitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTextInitLayout.setVerticalGroup(
            PanelTextInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTextInitLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(PanelTextInit);
        PanelTextInit.setBounds(50, 241, 790, 160);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(12, 210, 789, 2);

        PanelTextCript.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Output crypted text", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial Narrow", 1, 18))); // NOI18N

        TextCript.setColumns(20);
        TextCript.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextCript.setLineWrap(true);
        TextCript.setRows(5);
        TextCript.setWrapStyleWord(true);
        TextCript.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(TextCript);

        javax.swing.GroupLayout PanelTextCriptLayout = new javax.swing.GroupLayout(PanelTextCript);
        PanelTextCript.setLayout(PanelTextCriptLayout);
        PanelTextCriptLayout.setHorizontalGroup(
            PanelTextCriptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTextCriptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTextCriptLayout.setVerticalGroup(
            PanelTextCriptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTextCriptLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(499, 499, 499))
        );

        getContentPane().add(PanelTextCript);
        PanelTextCript.setBounds(50, 410, 789, 177);

        BrowseField.setEnabled(false);
        BrowseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseFieldActionPerformed(evt);
            }
        });

        Browse.setBackground(new java.awt.Color(204, 204, 204));
        Browse.setMnemonic('B');
        Browse.setText("Browse");
        Browse.setToolTipText("Click here to choose a file..");
        Browse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BrowseMouseClicked(evt);
            }
        });
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BrowseField, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Browse)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BrowseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Browse))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(173, 13, 536, 51);

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(810, 600, 59, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/criptare/pizza1_o.png"))); // NOI18N
        jButton1.setAutoscrolls(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 10, 180, 180);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/criptare/pizza1.png"))); // NOI18N
        jButton2.setAutoscrolls(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(710, 10, 180, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String filename;
    int length;
    int index;
    public void OpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenButtonActionPerformed
        // TODO add your handling code here:
        try {
            FileReader reader = new FileReader(filename);
            BufferedReader br = new BufferedReader(reader);
            TextInit.read(br, null);
            br.close();
            TextInit.requestFocus();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog (null, e);
        }
        
        length = TransformareBS.Citire(filename);
        
        Vernam x = new Vernam(index,length);
               try {
            FileReader reader1 = new FileReader("fisout.txt");
            BufferedReader br1 = new BufferedReader(reader1);
            TextCript.read(br1, null);
            br1.close();
            TextCript.requestFocus();
               }
        catch (Exception e) {
            JOptionPane.showMessageDialog (null, e);
        }
        
    }//GEN-LAST:event_OpenButtonActionPerformed

    public void BrowseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrowseFieldActionPerformed

    public void BrowseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrowseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BrowseMouseClicked

    public void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        JFileChooser browse = new JFileChooser();
        browse.showOpenDialog(null);
        File f = browse.getSelectedFile();
        filename = f.getAbsolutePath();
        BrowseField.setText(filename);
        
    }//GEN-LAST:event_BrowseActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        CriptareUI a = new CriptareUI();
        a.setVisible(true);
        close();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void OptListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptListActionPerformed
        // TODO add your handling code here:
        //String aux = (String) OptList.getSelectedItem();
        index = OptList.getSelectedIndex();
        System.out.print(index);

      
    }//GEN-LAST:event_OptListActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeniuCriptare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeniuCriptare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeniuCriptare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeniuCriptare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeniuCriptare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    public javax.swing.JButton Browse;
    private javax.swing.JTextField BrowseField;
    private javax.swing.JButton OpenButton;
    private javax.swing.JComboBox<String> OptList;
    private javax.swing.JPanel PanelKey;
    private javax.swing.JPanel PanelTextCript;
    private javax.swing.JPanel PanelTextCript1;
    private javax.swing.JPanel PanelTextInit;
    private javax.swing.JTextArea TextCript;
    private javax.swing.JTextArea TextCript1;
    private javax.swing.JTextArea TextInit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.ButtonGroup myOptionGroup;
    // End of variables declaration//GEN-END:variables
}
